Add vouchallengers to policy
Proof-Of-Humanity/poh-docs pull request #4
Opened 2022-10-25 15:21 UTC by herniadlf

Include vouchallengers definitions to Proof of Humanity policy. 

[Proposal](https://gov.proofofhumanity.id/t/phase-2-hip-58-removal-of-vouchallengers/2483?u=herniadlf)

2022-10-25 16:02 UTC, bilinkis requested changes
other than that comment, LGTM.

2022-10-25 16:02 UTC, bilinkis commented on policy.md
> +A vouchallenge is the act of using the vouch feature of registered humans to make the vouched profile vulnerable to a "Incorrect Submission" challenge. Once vouched, the challenge takes place (with t
to ask for *the* removal *of* those profiles

2022-10-25 20:20 UTC, herniadlf commented on policy.md
> +A vouchallenge is the act of using the vouch feature of registered humans to make the vouched profile vulnerable to a "Incorrect Submission" challenge. Once vouched, the challenge takes place (with t
fixed! Thx nico

2022-10-31 12:49 UTC, herniadlf commented
Final version, no more changes are allowed.

2023-01-04 16:09 UTC, luiandresgonzalez commented
Admission Criteria section needs to be updated as well.

2023-01-27 19:23 UTC, greenlucid commented
This PR was outdated after https://github.com/Proof-Of-Humanity/poh-docs/pull/5

2023-01-27 19:23 UTC, closed without merging